### ISSUE TITLE
Disappeared Settings page

### ISSUE THREAD

**Issue by Doc73** [nickjwhite/diogenes#9]
Dear Nick, in latest master branch disappeared settings page.
Obviously, it works with an old profile, but does not allow you to create a new one.

**Comment by nickjwhite** [comment]
Hi @Doc73, thanks for taking a look at the new changes! We're planning to add a link back to the settings page from a menu in the GUI (the electron window) soon, which is why I took the link off the homepage. Also, most of the settings are no longer useful, so I plan to trim the settings page down anyway.

But regardless, you're certainly right that we need a way to access the settings, so I'll keep this open until that's done.

Keep on reporting anything else you find, I can't tell you how grateful I am that you're looking around filing issues!

**Comment by Doc73** [comment]
Settings are back in latest master branch.
Many thanks!
